{% set name = "analisi" %}
{% set version = "0.3.1" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rikigigi/analisi/archive/v{{ version }}.tar.gz
  sha256: 9db15293f0515728ef83db7fedcd89a2dd5abeccdb3e11d79f97bc5c8e287200

build:
  number: {{ build }}
  skip: true  # [win]
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ mpi }}_{{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - {{ mpi }}
    - fftw
    - boost-cpp
    - eigen
    - xdrfile
  run:
    - python
    - {{ mpi }}
    - fftw
    - boost-cpp
    - xdrfile
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - pyanalisi
  requires:
    - pytest
    - pandas
    - pytest-regressions
  source_files:
    - tests
  commands:
    - export OMPI_MCA_plm=isolated                          # [mpi == "openmpi"]
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none  # [mpi == "openmpi"]
    - export OMPI_MCA_rmaps_base_oversubscribe=yes          # [mpi == "openmpi"]
    - export OMPI_ALLOW_RUN_AS_ROOT=1                       # [mpi == "openmpi"]
    - export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1               # [mpi == "openmpi"]
    - analisi_serial
    - mpiexec -n 1 analisi
    - pytest -v tests
about:
  home: https://github.com/rikigigi/analisi
  license: GPL-2.0-or-later
  license_file:
    - LICENSE

  summary: 'analisi: your Swiss Army Knife of molecular dynamics analysis'
  description: |
    analisi is a framework for analyzing molecular dynamics simulations.
    It can read lammps's binary format (other formats can be converted)
    and evaluate averages over the ergodic and equilibrated trajectory. 
    Very heavy calculation can be performed in a parallel way using 
    MPI, while multithreading is implemented also in the python interface.

  dev_url: https://github.com/rikigigi/analisi

extra:
  recipe-maintainers:
    - rikigigi
