{% set name = "analisi" %}
{% set version = "0.5.0" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/rikigigi/analisi.git
  git_rev: v{{ version }}
  git_depth: 1


build:
  number: {{ build }}
  skip: true  # [ python_impl == 'pypy' ]
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ mpi }}_{{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ mpi }}                              # [build_platform != target_platform and not win]

  host:
    - python
    - {{ mpi }}        # [ not win ]
    - fftw
    - boost-cpp
    - eigen
    - xdrfile          # [ not win ]
  run:
    - python
    - {{ mpi }}        # [ not win ]
    - fftw
    - boost-cpp
    - xdrfile          # [ not win ]
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - pyanalisi
  requires:
    - pytest
    - pandas
    - pytest-regressions
    - matplotlib
    - numpy
    - scipy
    - testbook
    - k3d
  source_files:
    - tests
    - tools
  commands:
    - export OMPI_MCA_plm=isolated                          # [not win and mpi == "openmpi"]
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none  # [not win and mpi == "openmpi"]
    - export OMPI_MCA_rmaps_base_oversubscribe=yes          # [not win and mpi == "openmpi"]
    - export OMPI_ALLOW_RUN_AS_ROOT=1                       # [not win and mpi == "openmpi"]
    - export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1               # [not win and mpi == "openmpi"]
    - analisi_serial --help                                 # [not win]
    - mpiexec -n 1 analisi --help                           # [not win]
    - pytest -sv tests
about:
  home: https://github.com/rikigigi/analisi
  license: GPL-2.0-or-later
  license_file:
    - LICENSE

  summary: 'analisi: your Swiss Army Knife of molecular dynamics analysis'
  description: |
    analisi is a framework for analyzing molecular dynamics simulations.
    It can read lammps's binary format (other formats can be converted)
    and evaluate averages over the ergodic and equilibrated trajectory. 
    Very heavy calculation can be performed in a parallel way using 
    MPI, while multithreading is implemented also in the python interface.

  dev_url: https://github.com/rikigigi/analisi

extra:
  recipe-maintainers:
    - rikigigi
